scripts: Add support for running http_server-cpp
unikraft/app-elfloader pull request #32
Opened 2023-09-24 20:58 UTC by chococandy63

2023-09-24 21:18 UTC, razvand commented
@chococandy63 , what is this issue for?

2023-09-25 16:21 UTC, razvand requested changes
Use `run.yaml:` instead of `scripts:` as prefix for commit message.

2023-09-25 16:21 UTC, razvand commented on scripts/run.yaml
> +  - name: http_server
```suggestion
  - name: http_server-cpp
```

To differentiate it from other servers.

2023-09-25 16:22 UTC, razvand commented
10 HP

2023-09-25 19:08 UTC, chococandy63 commented
@razvand I have made all the changes, kindly review them again.

2023-10-18 21:42 UTC, razvand approved these changes
Reviewed-by: Razvan Deaconescu <razvand@unikraft.io>
Approved-by: Razvan Deaconescu <razvand@unikraft.io>

2023-10-18 21:53 UTC, merged