Align the stack pointer at a 16-byte boundary at function calls
unikraft/app-elfloader pull request #9
Opened 2023-03-18 16:35 UTC by csvancea

x86_64 callees assume that the stack is 16-byte aligned. Ignoring this requirement might lead to crashes if the Linux ELFs use vectorized instructions to read from/write to the stack (eg: for copying arguments).

This PR fixes the problem by counting how many arguments are supposed to be pushed to the stack and if the number is odd, we push one more argument on top of the stack, before the auxiliary vector. This guarantees that the stack will be properly aligned when the execution starts at the ELF entry point.

Closes #8.

2023-03-27 18:56 UTC, skuenzer requested changes
Hi @csvancea,

thanks a lot for this PR. Can you update it so that we can achieve better architecture independence by using `UKARCH_SP_ALIGN`? I assume we then need to take into account the number of auxiliary vector entries that we push on the stack, as well. The auxiliary vector is like the environment variables and the application arguments: It is just a list of entries of size: `2 * sizeof(long)`: https://refspecs.linuxfoundation.org/LSB_1.3.0/IA64/spec/auxiliaryvector.html It does not have to be fixed size.

Thanks,

Simon

2023-04-14 00:17 UTC, skuenzer requested changes
Hi @csvancea, thanks a lot for this revision. Since your second commit removes all changes from the first commit it is probably not worth to keep the first commit. You can merge them together so that we have only one commit for this PR. I have some minor suggestions to improve code readability but other from this, it looks fine. 👍🏻 
Simon

2023-04-14 00:17 UTC, skuenzer commented on elf_ctx.c
> +		{ AT_NULL, 0x0 },
For readability, maybe put these entries in the right order and iterate in reverse order over them when pushing to the stack.

2023-04-14 00:17 UTC, skuenzer commented on elf_ctx.c
> +		{ AT_NULL, 0x0 },
Similar to `environ` and `argv`, I would push the terminating `AT_NULL` before entering the "stackpush-loop" (and not part of this array). This way the code could potentially cleanly handle an empty `auxv` vector.

2023-04-14 00:17 UTC, skuenzer commented on elf_ctx.c
> +	ctx->sp -= (UKARCH_SP_ALIGN - (stackval_len & UKARCH_SP_ALIGN_MASK)) & UKARCH_SP_ALIGN_MASK;
Can you use the `ALIGN_DOWN()` or `ALIGN_UP()` macro instead (`<uk/essentials.h>`)? It does basically the same but is maybe quicker to read. Ideally, the computation does not do any assumption on the current alignemnt of the stack and just aligns it properly. We can then later add more things on the stack before the padding without risking to break any of the alignment logic (e.g., a copy of `argv` and `envp` strings: http://articles.manugarg.com/aboutelfauxiliaryvectors.html)

2023-04-14 00:17 UTC, skuenzer commented on elf_ctx.c
> +	stackvalc = AUXV_VALUES_PER_ENTRY * ARRAY_SIZE(auxv) + (envc+1) + ((argc-1)+2);
Instead of AUXV_VALUES_PER_ENTRY, you could also use `sizeof(struct aux_vector_entry)`.

2023-04-14 00:17 UTC, skuenzer commented on elf_ctx.c
> +		ukarch_rctx_stackpush(ctx, auxv[i].key);
Does `ukarch_rctx_stackpush(ctx, auxv[i]);` work, too? If so, I'd prefer that as good practice: Preferably deriving everything from the `struct auxv_entry` definition.

2023-04-14 00:17 UTC, skuenzer commented on elf_ctx.c
> +	int i, envc, stackvalc, stackval_len;
Maybe you want to cal it `elfvec_len` for `ELF vectors length`? The count may no be needed if you update the computation formular.

2023-04-14 00:17 UTC, skuenzer commented on elf_ctx.c
> +struct aux_vector_entry {
I'd probably call it `auxv_entry`

2023-04-14 00:17 UTC, skuenzer commented on elf_ctx.c
> +	ctx->sp -= (UKARCH_SP_ALIGN - (stackval_len & UKARCH_SP_ALIGN_MASK)) & UKARCH_SP_ALIGN_MASK;
I am thinking of something like (please double-check):
```c
ctx->sp = ALIGN_DOWN(ctx->sp - elfvec_len, UKARCH_SP_ALIGN) + elfvec_len;
```

2023-04-14 00:23 UTC, skuenzer commented on elf_ctx.c
> +	stackvalc = AUXV_VALUES_PER_ENTRY * ARRAY_SIZE(auxv) + (envc+1) + ((argc-1)+2);
You could directly compute `elfvec_len` and using `sizeof()`s for each entry item size, like:
```c
elfvec_len = (ARRAY_SIZE(auxv) * sizeof(struct auxv_entry))
             + (envc + 1) * sizeof(uintptr_t)
             + (argc + 1) * sizeof(uintptr_t);
```

2023-04-14 17:09 UTC, csvancea commented on elf_ctx.c
> +	ctx->sp -= (UKARCH_SP_ALIGN - (stackval_len & UKARCH_SP_ALIGN_MASK)) & UKARCH_SP_ALIGN_MASK;
Thanks for the improved formula! I always thought that there were ways to simplify it, but couldn't find how to do it.

Compared the result of both calculations and they yield the same results.

2023-04-14 17:10 UTC, csvancea commented on elf_ctx.c
> +		ukarch_rctx_stackpush(ctx, auxv[i].key);
It works and definitely it looks better.

2023-04-14 17:24 UTC, csvancea commented on elf_ctx.c
> +		{ AT_NULL, 0x0 },
I don't think the order matters as long `AT_NULL` is the first value pushed. Anyway, while reversing the order, I have noticed that `AT_SYSINFO` was being pushed twice, so I have removed one entry.

2023-04-18 21:16 UTC, skuenzer approved these changes
Thanks for the updates!

Reviewed-by: Simon Kuenzer <simon@unikraft.io>
Approved-by: Simon Kuenzer <simon@unikraft.io>

2023-04-21 15:25 UTC, closed without merging